name: vaultwarden

services:
  vaultwarden-app:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden-app
    hostname: vaultwarden
    env_file: .env
    restart: unless-stopped
    networks:
      - vaultwarden-net
    environment:
      DOMAIN: https://${DOMAIN}
      ADMIN_TOKEN: CHANGE-ME
      TZ: ${TZ}
      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGN-UPS_ALLOWED}
    volumes:
      - vaultwarden-app:/data:Z
    ports:
      - "127.0.0.1:8001:80"
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
     interval: 30s
     timeout: 10s
     retries: 3
     start_period: 10s
    secrets:
      - vaultwarden_admin_token
      - vaultwarden_smtp_password
    cpus: ${VAULTWARDEN_CPU_LIMIT}
    mem_limit: ${VAULTWARDEN_MEM_LIMIT}
    security_opt:
      - no-new-privileges:true

volumes:
  vaultwarden-app:

networks:
  vaultwarden-net:
