#Invoiceninja YAML File Docker/Podman Compose
name: invoiceninja

services:
  invoiceninja-db:
    image: docker.io/library/mariadb:11
    container_name: invoiceninja-db
    hostname: invoiceninja-db
    restart: unless-stopped
    networks:
      - invoiceninja-net
    env_file: immich.env
    volumes:
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-db-backups:/var/db-backups:Z
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-db:/var/lib/mysql:Z
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 120s
      timeout: 10s
      retries: 15
      start_period: 60s
    mem_limit: 2g
    security_opt:
      - no-new-privileges:true

  invoiceninja-redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: invoiceninja-redis
    hostname: invoiceninja-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -a ping | grep PONG"]
      interval: 120s
      timeout: 15s
      retries: 5
    networks:
      - invoiceninja-net
    env_file: immich.env
    volumes:
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-valkey:/data:Z
    mem_limit: 2g
    security_opt:
      - no-new-privileges:true

  invoiceninja-app:
    image: docker.io/invoiceninja/invoiceninja-debian:latest
    container_name: invoiceninja-app
    hostname: invoiceninja-app
    restart: unless-stopped
    depends_on:
      invoiceninja-db:
        condition: service_healthy
      invoiceninja-redis:
        condition: service_healthy
    env_file: immich.env
    networks:
      - invoiceninja-net
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm >/dev/null || exit 1"]
      interval: 120s
      timeout: 15s
      retries: 15
    volumes:
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-public:/var/www/html/public:z
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-storage:/var/www/html/storage:z
    mem_limit: 2g
    security_opt:
      - no-new-privileges:true

  invoiceninja-nginx:
    image: docker.io/nginx:alpine
    container_name: invoiceninja-nginx
    hostname: invoiceninja-nginx
    restart: unless-stopped
    depends_on:
      invoiceninja-app:
        condition: service_healthy
    networks:
      - invoiceninja-net
    ports:
      - "127.0.0.1:8004:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ >/dev/null || exit 1"]
      interval: 120s
      timeout: 15s
      retries: 15
      start_period: 90s
    env_file: immich.env
    volumes:
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-public:/var/www/html/public:ro,z
      - /home/invoiceninja/.data/invoiceninja/invoiceninja-storage:/var/www/html/storage:ro,z
      - /home/invoiceninja/.data/invoiceninja/nginx:/etc/nginx/conf.d:ro,Z
    mem_limit: 2g
    security_opt:
      - no-new-privileges:true

networks:
  invoiceninja-net:
    driver: bridge
    name: invoiceninja-net
